apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app.kubernetes.io/name: memcached
spec:
  selector:
    app.kubernetes.io/name: memcached
  ports:
    - name: memcached
      port: 11211
      targetPort: memcached
