apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s95
resources:
  - namespace.yaml
  - configmap-env.yaml
  - configmap-additional-events.yaml
  - pvc-storage.yaml
  - service.yaml
  - web-deployment.yaml
  - sidekiq-deployment.yaml
  - ingress.yaml
  - migrate-job.yaml
  - cronjobs/pghero-clean.yaml
  - cronjobs/invite-newbies.yaml
  - cronjobs/parkzhrun.yaml
  - cronjobs/sitemap.yaml
  - cronjobs/doubled-results.yaml
  - cronjobs/incorrect-activities.yaml
images:
  - name: registry.sion2k.ru/s95/web
    newTag: f57d1537
